/**
 * Document Generation Type Definitions
 *
 * @module types/documents
 * @see {@link DataFlowTypes} for complete data flow documentation
 */

/**
 * Represents a structured content section within a document
 *
 * @interface DocumentSection
 * @property {string} content - The text content of the section
 * @property {unknown} [key] - Additional dynamic properties for section metadata
 *
 * @example
 * const section: DocumentSection = {
 *   content: "This is the introduction section...",
 *   heading_level: 2,
 *   section_id: "intro"
 * };
 */
export interface DocumentSection {
  content: string;
  [key: string]: unknown;
}

/**
 * Validation result for document generation processes
 *
 * @interface DocumentValidationResult
 * @property {boolean} isValid - Whether the document passed validation
 * @property {string[]} errors - Critical errors that prevent document generation
 * @property {string[]} warnings - Non-critical warnings about document quality
 *
 * @example
 * const result: DocumentValidationResult = {
 *   isValid: false,
 *   errors: ["Missing required field: principal_investigator"],
 *   warnings: ["Timeline may be too short for HREC review"]
 * };
 */
export interface DocumentValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

/**
 * Types of documents that can be generated by the system
 *
 * Each document type corresponds to a specific template and generator class.
 * This is the canonical enum - do not create local type aliases.
 *
 * @enum {string}
 *
 * @property {string} RESEARCH_PROTOCOL - Full research protocol for HREC submission
 * @property {string} QI_PROJECT_PLAN - Quality improvement project plan
 * @property {string} EMF_APPLICATION - Emergency Medicine Foundation grant application
 * @property {string} HREC_COVER_LETTER - Cover letter for HREC application package
 * @property {string} PICF - Participant Information and Consent Form
 * @property {string} DATA_MANAGEMENT_PLAN - Data management and governance plan
 * @property {string} SITE_ASSESSMENT - Site-specific assessment form
 * @property {string} LNR_APPLICATION - Low/Negligible Risk application form
 */
export enum DocumentType {
  RESEARCH_PROTOCOL = 'RESEARCH_PROTOCOL',
  QI_PROJECT_PLAN = 'QI_PROJECT_PLAN',
  EMF_APPLICATION = 'EMF_APPLICATION',
  HREC_COVER_LETTER = 'HREC_COVER_LETTER',
  PICF = 'PICF',
  DATA_MANAGEMENT_PLAN = 'DATA_MANAGEMENT_PLAN',
  SITE_ASSESSMENT = 'SITE_ASSESSMENT',
  LNR_APPLICATION = 'LNR_APPLICATION'
}

/**
 * Lifecycle status of a generated document
 *
 * @enum {string}
 *
 * @property {string} DRAFT - Initial generated version, not yet reviewed
 * @property {string} PENDING_REVIEW - Submitted for review by research team
 * @property {string} APPROVED - Approved by reviewers, ready for submission
 * @property {string} REJECTED - Rejected, requires revision
 * @property {string} FINAL - Final version submitted to ethics committee
 */
export enum DocumentStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FINAL = 'FINAL'
}

/**
 * Metadata about a generated document
 *
 * @interface DocumentMetadata
 * @property {string} project_id - UUID of the associated project
 * @property {string} version - Semantic version (e.g., "1.0.0")
 * @property {string} generated_at - ISO 8601 timestamp of generation
 * @property {number} [total_pages] - Total page count (estimated)
 * @property {number} [word_count] - Total word count
 *
 * @example
 * const metadata: DocumentMetadata = {
 *   project_id: "123e4567-e89b-12d3-a456-426614174000",
 *   version: "1.0.0",
 *   generated_at: "2026-01-30T10:30:00Z",
 *   total_pages: 45,
 *   word_count: 12500
 * };
 */
export interface DocumentMetadata {
  project_id: string;
  version: string;
  generated_at: string;
  total_pages?: number;
  word_count?: number;
}

/**
 * Database record of a generated document
 *
 * Stored in the `generated_documents` table and linked to a project.
 *
 * @interface GeneratedDocument
 * @property {string} id - Unique document ID (UUID)
 * @property {string} project_id - Associated project ID (UUID)
 * @property {DocumentType} document_type - Type of document generated
 * @property {string} filename - Output filename (e.g., "Protocol_v1.0.0.docx")
 * @property {string} file_path - Storage path or URL
 * @property {number} [file_size] - File size in bytes
 * @property {string} [mime_type] - MIME type (typically "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
 * @property {string} version - Document version
 * @property {DocumentStatus} status - Current document status
 * @property {string} created_at - ISO 8601 creation timestamp
 * @property {DocumentMetadata} [metadata] - Additional metadata
 *
 * @example
 * const doc: GeneratedDocument = {
 *   id: "doc-uuid",
 *   project_id: "proj-uuid",
 *   document_type: DocumentType.RESEARCH_PROTOCOL,
 *   filename: "Protocol_v1.0.0.docx",
 *   file_path: "/output/documents/doc-uuid.docx",
 *   file_size: 524288,
 *   mime_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
 *   version: "1.0.0",
 *   status: DocumentStatus.DRAFT,
 *   created_at: "2026-01-30T10:30:00Z"
 * };
 */
export interface GeneratedDocument {
  id: string;
  project_id: string;
  document_type: DocumentType;
  filename: string;
  file_path: string;
  file_size?: number;
  mime_type?: string;
  version: string;
  status: DocumentStatus;
  created_at: string;
  metadata?: DocumentMetadata;
}

/**
 * Output package from the document generation stage
 *
 * Contains all generated documents plus metadata for submission planning.
 *
 * @interface DocumentsOutput
 * @property {GeneratedDocument[]} generated - Array of all generated documents
 * @property {string[]} pending_review - Document IDs awaiting review
 * @property {Object} metadata - Package-level metadata
 * @property {number} metadata.total_documents - Total number of documents generated
 * @property {Array} metadata.submission_checklist - Checklist of required documents
 * @property {number} metadata.estimated_pages - Total estimated page count for all documents
 *
 * @example
 * const output: DocumentsOutput = {
 *   generated: [protocolDoc, picfDoc, dmpDoc],
 *   pending_review: ["doc-uuid-1"],
 *   metadata: {
 *     total_documents: 3,
 *     submission_checklist: [
 *       { document_type: DocumentType.RESEARCH_PROTOCOL, required: true, status: "complete" },
 *       { document_type: DocumentType.PICF, required: true, status: "complete" }
 *     ],
 *     estimated_pages: 75
 *   }
 * };
 */
export interface DocumentsOutput {
  generated: GeneratedDocument[];
  pending_review: string[];
  metadata: {
    total_documents: number;
    submission_checklist: {
      document_type: DocumentType;
      required: boolean;
      status: string;
    }[];
    estimated_pages: number;
  };
}
