/**
 * Research Brief Generation Module
 * Phase 4.8 - Generate Markdown research brief from intake data
 *
 * Creates a structured research brief document that:
 * - Summarizes intake data
 * - Includes classification results
 * - Lists framework requirements
 * - Provides context for Research Agent
 */

import type { Project, IntakeData, Classification, Frameworks } from '../../types/index.js';

/**
 * Generate research brief in Markdown format
 *
 * Creates a comprehensive research brief document for the Research Agent,
 * including project details, classification, and framework requirements.
 *
 * @param project - Complete project record after intake processing
 * @returns Formatted Markdown research brief
 *
 * @example
 * ```typescript
 * const brief = generateResearchBrief(project);
 * console.log(brief);
 * // # Research Brief: ED Triage Protocol
 * // ## Project Classification: QI (confidence: 0.92)
 * // ...
 * ```
 */
export function generateResearchBrief(project: Project): string {
  const { intake, classification, frameworks } = project;

  const sections: string[] = [];

  // Title
  sections.push(`# Research Brief: ${intake.project_title}`);
  sections.push('');
  sections.push(`**Project ID:** ${project.id}`);
  sections.push(`**Generated:** ${new Date().toISOString()}`);
  sections.push('');
  sections.push('---');
  sections.push('');

  // Classification Summary
  sections.push('## Project Classification');
  sections.push('');
  sections.push(formatClassification(classification));
  sections.push('');

  // Project Overview
  sections.push('## Project Overview');
  sections.push('');
  sections.push(formatProjectOverview(intake));
  sections.push('');

  // Clinical Context
  sections.push('## Clinical Context');
  sections.push('');
  sections.push(formatClinicalContext(intake));
  sections.push('');

  // Investigators
  sections.push('## Research Team');
  sections.push('');
  sections.push(formatInvestigators(intake));
  sections.push('');

  // Framework Requirements
  sections.push('## Framework Requirements');
  sections.push('');
  sections.push(formatFrameworks(frameworks));
  sections.push('');

  // Timeline
  if (intake.timeline_constraint) {
    sections.push('## Timeline Constraints');
    sections.push('');
    sections.push(formatTimeline(intake.timeline_constraint));
    sections.push('');
  }

  // Research Agent Instructions
  sections.push('## Instructions for Research Agent');
  sections.push('');
  sections.push(generateResearchInstructions(classification, intake));
  sections.push('');

  // Metadata footer
  sections.push('---');
  sections.push('');
  sections.push(`*Generated by QI/Research Pipeline - Intake Agent*`);
  sections.push(`*Status: ${project.status}*`);

  return sections.join('\n');
}

/**
 * Format classification section
 */
function formatClassification(classification: Classification): string {
  const lines: string[] = [];

  lines.push(`**Type:** ${classification.project_type}`);
  lines.push(`**Confidence:** ${(classification.confidence * 100).toFixed(1)}%`);
  lines.push('');

  lines.push('**Reasoning:**');
  lines.push(classification.reasoning);
  lines.push('');

  if (classification.suggested_designs.length > 0) {
    lines.push('**Suggested Study Designs:**');
    classification.suggested_designs.forEach(design => {
      lines.push(`- ${design}`);
    });
  }

  return lines.join('\n');
}

/**
 * Format project overview section
 */
function formatProjectOverview(intake: IntakeData): string {
  const lines: string[] = [];

  lines.push(`**Project Type:** ${intake.project_type}`);
  lines.push('');

  lines.push('**Concept:**');
  lines.push(intake.concept_description);
  lines.push('');

  lines.push('**Intended Outcomes:**');
  lines.push(intake.intended_outcomes);
  lines.push('');

  if (intake.grant_target) {
    lines.push(`**Grant Target:** ${intake.grant_target}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Format clinical context section
 */
function formatClinicalContext(intake: IntakeData): string {
  const lines: string[] = [];

  lines.push('**Clinical Problem:**');
  lines.push(intake.clinical_problem);
  lines.push('');

  lines.push(`**Target Population:** ${intake.target_population}`);
  lines.push('');

  lines.push(`**Setting:** ${intake.setting}`);

  return lines.join('\n');
}

/**
 * Format investigators section
 */
function formatInvestigators(intake: IntakeData): string {
  const lines: string[] = [];

  // Principal Investigator
  lines.push('**Principal Investigator:**');
  const pi = intake.principal_investigator;
  lines.push(`- **Name:** ${pi.name}`);
  lines.push(`- **Title:** ${pi.title}`);
  lines.push(`- **Institution:** ${pi.institution}`);
  lines.push(`- **Department:** ${pi.department}`);
  lines.push(`- **Email:** ${pi.email}`);
  if (pi.expertise && pi.expertise.length > 0) {
    lines.push(`- **Expertise:** ${pi.expertise.join(', ')}`);
  }
  lines.push('');

  // Co-Investigators
  if (intake.co_investigators && intake.co_investigators.length > 0) {
    lines.push('**Co-Investigators:**');
    intake.co_investigators.forEach((coInv, index) => {
      lines.push(`${index + 1}. **${coInv.name}** (${coInv.title})`);
      lines.push(`   - Institution: ${coInv.institution}`);
      lines.push(`   - Role: ${coInv.role}`);
      if (coInv.expertise && coInv.expertise.length > 0) {
        lines.push(`   - Expertise: ${coInv.expertise.join(', ')}`);
      }
    });
  }

  return lines.join('\n');
}

/**
 * Format frameworks section
 */
function formatFrameworks(frameworks: Frameworks): string {
  const lines: string[] = [];

  lines.push(`**Reporting Guideline:** ${frameworks.reporting_guideline}`);
  lines.push('');

  lines.push(`**Ethics Framework:** ${frameworks.ethics_framework}`);
  lines.push('');

  lines.push('**Governance Requirements:**');
  frameworks.governance_requirements.forEach(req => {
    lines.push(`- ${req.replace(/_/g, ' ')}`);
  });

  return lines.join('\n');
}

/**
 * Format timeline constraints section
 */
function formatTimeline(timeline: { submission_deadline?: string; completion_deadline?: string; grant_deadline?: string; notes?: string }): string {
  const lines: string[] = [];

  if (timeline.submission_deadline) {
    lines.push(`**Submission Deadline:** ${timeline.submission_deadline}`);
  }

  if (timeline.completion_deadline) {
    lines.push(`**Completion Deadline:** ${timeline.completion_deadline}`);
  }

  if (timeline.grant_deadline) {
    lines.push(`**Grant Deadline:** ${timeline.grant_deadline}`);
  }

  if (timeline.notes) {
    lines.push('');
    lines.push('**Notes:**');
    lines.push(timeline.notes);
  }

  return lines.join('\n');
}

/**
 * Generate instructions for Research Agent
 */
function generateResearchInstructions(classification: Classification, intake: IntakeData): string {
  const lines: string[] = [];

  lines.push('The Research Agent should focus on:');
  lines.push('');

  // Type-specific instructions
  if (classification.project_type === 'QI') {
    lines.push('1. **QI-Specific Literature:**');
    lines.push('   - Similar improvement initiatives in emergency departments');
    lines.push('   - Implementation science literature on change management');
    lines.push('   - Baseline performance metrics from comparable settings');
    lines.push('');
    lines.push('2. **Evidence for Intervention Effectiveness:**');
    lines.push(`   - Does the proposed approach work? (${intake.concept_description.slice(0, 100)}...)`);
    lines.push('   - What are the key success factors?');
    lines.push('   - What barriers and facilitators have been reported?');
    lines.push('');
  } else if (classification.project_type === 'RESEARCH') {
    lines.push('1. **Systematic Literature Review:**');
    lines.push('   - Comprehensive search of relevant databases (PubMed, Cochrane, etc.)');
    lines.push('   - Include systematic reviews, RCTs, and observational studies');
    lines.push('   - Focus on high-quality evidence');
    lines.push('');
    lines.push('2. **Knowledge Gaps:**');
    lines.push('   - What questions remain unanswered?');
    lines.push('   - What methodological approaches are needed?');
    lines.push('   - How does this project address the gaps?');
    lines.push('');
  } else {
    lines.push('1. **Dual Focus:**');
    lines.push('   - QI implementation evidence');
    lines.push('   - Research evidence for generalisability');
    lines.push('');
  }

  // Common instructions
  lines.push('3. **Search Strategy:**');
  lines.push(`   - Population: ${intake.target_population}`);
  lines.push(`   - Problem: ${intake.clinical_problem}`);
  lines.push(`   - Outcomes: ${intake.intended_outcomes}`);
  lines.push('');

  lines.push('4. **Output Requirements:**');
  lines.push('   - Evidence synthesis (1500 words max)');
  lines.push('   - Gap analysis');
  lines.push('   - Formatted citations (Vancouver style)');
  lines.push('   - Key findings extraction');

  return lines.join('\n');
}
